# Generated by Django 6.0.5 on 2026-06-07 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsetup',
            name='appliance_data',
        ),
        migrations.RemoveField(
            model_name='savedsetup',
            name='setup_name',
        ),
        migrations.AddField(
            model_name='savedsetup',
            name='ips_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedsetup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SetupAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('custom_watt', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appliance')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.savedsetup')),
            ],
        ),
    ]
