# Generated by Django 6.0.5 on 2026-06-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_savedsetup_appliance_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='battery_percentage',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='battery_voltage',
        ),
    ]
