# Generated by Django 6.0.5 on 2026-07-27 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notice_is_pinned_schedule_created_at_and_more'),
        ('users', '0003_remove_userprofile_battery_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.area'),
        ),
        migrations.CreateModel(
            name='SavedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Home', max_length=80)),
                ('email_alerts', models.BooleanField(default=True)),
                ('alert_minutes_before', models.PositiveIntegerField(default=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'area', 'label')},
            },
        ),
    ]
