from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.home,
        name='home'
    ),

    path(
        'home/',
        views.home,
        name='home'
    ),

    path(
        'schedule/',
        views.schedule,
        name='schedule'
    ),

    path(
        'ajax/get-upazilas/',
        views.get_upazilas,
        name='get_upazilas'
    ),

    path(
        'ajax/get-areas/',
        views.get_areas,
        name='get_areas'
    ),

    path(
        'notice/',
        views.notice_view,
        name='notices'
    ),
    path(
        'feedback/',
        views.feedback_create,
        name='feedback_create'
    ),
    path(
        'management/',
        views.management_dashboard,
        name='management_dashboard'
    ),
    path(
        'management/schedules/',
        views.management_schedules,
        name='management_schedules'
    ),
    path(
        'management/schedules/save/',
        views.management_schedule_save,
        name='management_schedule_create'
    ),
    path(
        'management/schedules/<int:schedule_id>/save/',
        views.management_schedule_save,
        name='management_schedule_update'
    ),
    path(
        'management/schedules/<int:schedule_id>/delete/',
        views.management_schedule_delete,
        name='management_schedule_delete'
    ),
    path(
        'management/schedules/export/',
        views.management_schedule_export,
        name='management_schedule_export'
    ),
    path(
        'management/schedules/import/',
        views.management_schedule_import,
        name='management_schedule_import'
    ),
    path(
        'management/notices/',
        views.management_notices,
        name='management_notices'
    ),
    path(
        'management/notices/save/',
        views.management_notice_save,
        name='management_notice_create'
    ),
    path(
        'management/notices/<int:notice_id>/save/',
        views.management_notice_save,
        name='management_notice_update'
    ),
    path(
        'management/feedback/',
        views.management_feedback,
        name='management_feedback'
    ),
    path(
        'management/feedback/<int:report_id>/',
        views.management_feedback_update,
        name='management_feedback_update'
    ),
]
